version: '2'

services:
    go_server_common:
      build: ./
      container_name: go_user_server
      environment:
         FILE_SERVER_NAME: "www.52db.xyz"
         RESTY_CONFIG_OPTIONS_MORE: "--with-echo_nginx_module"
      ports:
         - "80:80"
      network_mode: host
      volumes:
        - ../:/apps
        - ./conf/nginx:/etc/nginx
        #consul-template
        - ./consul-template:/consul-template
        - ./consul-template/consul-template:/usr/local/bin/consul-template
        # 日志存放路径，需要同级目录创建本目录
        - ./supervisor:/supervisor
        - ../logs:/apps/logs
        - ./conf/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx_template.conf
      command: /sh/start.sh


